---
# tasks file for cassandra

- name: Configure the Apache Cassandra YUM Repository
  yum_repository:
    name: cassandra
    baseurl: "https://www.apache.org/dist/cassandra/redhat/{{ cassandra_repo_apache_release }}/"
    gpgcheck: yes
    description: Apache Cassandra
    repo_gpgcheck: yes
    gpgkey: https://www.apache.org/dist/cassandra/KEYS
  when:
    - ansible_os_family is defined
    - ansible_os_family == 'RedHat'

- name: Add the Apache Apt Keys
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: "{{ item }}"
  register: cassandra_remote_status
  until: cassandra_remote_status is succeeded
  delay: "{{ cassandra_task_delay }}"
  retries: "{{ cassandra_task_retries }}"
  with_items:
    - A278B781FE4B2BDA
    - E91335D77E3E87CB
  when:
    - ansible_os_family is defined
    - ansible_os_family == 'Debian'

- name: Configure the Apache Cassandra Apt Repository
  apt_repository:
    filename: /etc/apt/sources.list.d/cassandra.sources
    repo: "deb http://www.apache.org/dist/cassandra/debian {{ cassandra_repo_apache_release }} main"
    state: present
  when:
    - ansible_os_family is defined
    - ansible_os_family == 'Debian'
