---
# Tasks for adding a standalone cluster to an existing cluster.
- name: Get Current Node Count If Available
  shell:
    cmd: nodetool status | awk '/^(U|D)(N|L|J|M)/{print $2}' | wc -l
  register: cassandra_nodetool_output
  changed_when: false
  check_mode: no

- name: Store Current Node Count
  set_fact:
    cassandra_node_count: "{{ cassandra_nodetool_output.stdout }}"
  when:
    - not ansible_check_mode

- name: Stop Cassandra (RedHat)
  systemd:
    name: cassandra
    state: stopped
  when:
    - cassandra_node_count is defined
    - cassandra_node_count == '1'
    - not ansible_check_mode
    - ansible_os_family is defined
    - ansible_os_family == 'RedHat'

- name: Stop Cassandra (Debian)
  service:
    name: cassandra
    state: stopped
  when:
    - cassandra_node_count is defined
    - cassandra_node_count == '1'
    - not ansible_check_mode
    - ansible_os_family is defined
    - ansible_os_family == 'Debian'

- name: Clean Cassandra Data Directory
  file:
    state: absent
    path: "{{ cassandra_path }}/"
  when:
    - cassandra_node_count is defined
    - cassandra_node_count == '1'
    - cassandra_path is defined
    - cassandra_directories is not defined

- name: Clean Cassandra Data Directories
  file:
    state: absent
    path: "{{ item }}"
  with_items: "{{ cassandra_directories.keys() | list }}"
  when:
    - cassandra_node_count is defined
    - cassandra_node_count == '1'
    - cassandra_path is not defined
    - cassandra_directories is defined
