---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-data:
      ignore: molecule/default/molecule.yml

platforms:
  - name: centos7
    command: /usr/sbin/init
    groups:
      - cassandra
      - centos
    image: centos:7
    privileged: True

  - name: centos8
    command: /usr/sbin/init
    dockerfile: Dockerfile-centos8.j2
    groups:
      - cassandra
      - centos
      - python3
    image: centos:8
    privileged: True

  - name: debian9
    groups:
      - cassandra
      - debian
    image: debian:9

  - name: debian10
    groups:
      - cassandra
      - debian
    image: debian:buster

  - name: fedora29
    command: /usr/sbin/init
    groups:
      - cassandra
      - fedora
      - python3
    image: fedora:29
    privileged: True

  - name: fedora30
    command: /usr/sbin/init
    groups:
      - cassandra
      - fedora
      - python3
    image: fedora:30
    privileged: True

  - name: ubuntu1604
    command: /sbin/init
    groups:
      - cassandra
      - ubuntu
    image: ubuntu:16.04
    privileged: True

  - name: ubuntu1804
    image: ubuntu:18.04
    groups:
      - cassandra
      - ubuntu
    privileged: True

provisioner:
  name: ansible

  config_options:
    defaults:
      callback_whitelist: "profile_tasks,timer"

  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: python3

  log: True

  lint:
    name: ansible-lint

  options:
    limit: ${HOSTS}
    v: 1

scenario:
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - verify

verifier:

  name: testinfra

  options:
    connection: docker
    durations: 3
    v: 1

  lint:
    name: flake8
